### ISSUE TITLE
Not really an issue, but an "How to"

### ISSUE THREAD

**Issue by ImanoWilliams** [philgyford/django-nested-inline-formsets-example#1]
How can I write a Createview using your example? I am new to Django.

**Comment by philgyford** [comment]
I think the simplest thing would be to use a CreateView to create a Publisher (in my example) and then, once the Publisher exists, use the PublisherUpdateView to add Books to it.

It's probably possible to create a single form to create a Publisher and add Books to it but it would be more complicated because there's no Publisher to attach the books to. The view would have to create the Publisher and, assuming that works OK, *then* add all the Books to it. Not impossible, but it adds more complexity...

I can add a CreateView for the Publisher (the simplest option) if that would help you?

**Comment by philgyford** [comment]
I added a PublisherCreateView as it didn't take long!

I've also renamed the old PublisherUpdateView to PublisherBooksUpdateView, because it's only for adding/editing a Publisher's Books, rather than editing the details of a Publisher (like its name).

**Comment by jordan-bys** [comment]
i have a problem with my inlineformset please can you help me ? 
https://stackoverflow.com/questions/62252867/inline-formset-only-save-the-last-form 
i'm ready to pay please

**Comment by julialoh** [comment]
Hello! Thank you so much for this project- it's very helpful. I'm trying to create this all in one form so create publisher, books, and book images in one form. Do you have any guidance as to go about doing this? Thank you!
